### ISSUE TITLE
Game Various Game - Định kiểu CSS 

### ISSUE THREAD

**Issue by daipthraomng** [Cuong020900/Web_Application_Based_On_DragonLearn-Grade1-Operations-CalculationsUpTo5#10]
Định kiểu css theo giao diện thiết kế ban đầu.

**Comment by Cuong020900** [comment]
Đã xong

**Comment by Cuong020900** [comment]
Dựa vào mã HTML đã được thiết kễ, phần này sẽ make beautiful code đấy.
Yêu cầu: màu sắc dễ nhìn, hình ảnh phù hợp với thiếu nhi
