### ISSUE TITLE
Game Various Equations - Xử lý nhập số.

### ISSUE THREAD

**Issue by daipthraomng** [Cuong020900/Web_Application_Based_On_DragonLearn-Grade1-Operations-CalculationsUpTo5#11]
Xử lý sự kiện nhập số và kiểm tra đúng sai.

**Comment by Cuong020900** [comment]
Đã Xong

**Comment by Cuong020900** [comment]
Ở phần này, chúng ta xử lí sự kiện nhập số, nghĩa là:
+ Khi vào game, con trỏ tự focus vào ô nhập màn hình
+ Khi trả lời đúng 1 câu, nó focus vào câu thứ 2
+ Lúc nhập đúng sẽ báo
+ Lúc nhập chữ sẽ bị xóa, bắt nhập lại
