### ISSUE TITLE
Tạo âm thanh giọng đọc đề bài: Hiện 1 cái loa ở bên câu hỏi, lúc bấm vào đó sẽ đọc câu hỏi. 

### ISSUE THREAD

**Issue by daipthraomng** [Cuong020900/Web_Application_Based_On_DragonLearn-Grade1-Operations-CalculationsUpTo5#12]
Tạo âm thanh giọng đọc đề bài: Hiện 1 cái loa ở bên câu hỏi, lúc bấm vào đó sẽ đọc câu hỏi. Tìm API cho phép truyền file mp3 vào và phát.

**Comment by Cuong020900** [comment]
Yêu cầu:
Hiện 1 cái loa ở bên câu hỏi, lúc bấm vào đó sẽ đọc câu hỏi
Ý tưởng: lấy API từ google hoặc đâu đấy, gửi lên 1 đoạn text và sẽ nhận về file mp3, cho nó vào audio phát

**Comment by Cuong020900** [comment]
Vấn đề đang gặp phải: Hình cái loa xấu, chưa có hiệu ứng
Âm thanh phát sai khi dùng dấu "-"
