### ISSUE TITLE
Bài học Coloring - Xây dựng nội dung, phân chia bố cục game theo hình (link dưới phần mô tả) dùng ngôn ngữ HTML5

### ISSUE THREAD

**Issue by daipthraomng** [Cuong020900/Web_Application_Based_On_DragonLearn-Grade1-Operations-CalculationsUpTo5#14]
Xây dựng nội dung, phân chia bố cục game theo [hình ảnh bài học](https://github.com/Cuong020900/Web_Application_Based_On_DragonLearn-Grade1-Operations-CalculationsUpTo5/blob/master/assets/img/coloring.PNG) trên dragonlearn dùng ngôn ngữ HTML5.

**Comment by Cuong020900** [comment]
Tương tự với các phần khác, chúng ta dùng HTML để tạo bố cục, trật tự cơ bản cho trang web
Yêu cầu: 
+ Tương đối giống với game trên dragonlearn.in
+
