### ISSUE TITLE
Bài học Various Equations - Thiết kế bố cục.

### ISSUE THREAD

**Issue by daipthraomng** [Cuong020900/Web_Application_Based_On_DragonLearn-Grade1-Operations-CalculationsUpTo5#9]
Thiết kế bố cục với HTML5.

**Comment by Cuong020900** [comment]
Đã xong

**Comment by Cuong020900** [comment]
Bố cục gồm 2 thành phần chính là
+ Thanh điều hướng/menu
+ Màn hình chơi game
*Yêu cầu: thanh điều hướng được tạo sẵn, nó có ở tất cả màn hình nên ta chỉ cần tái sử dụng
Ở phần chơi game cần phân ra các màn hình rõ ràng: nút bắt đầu chơi, nút sang màn tiếp theo
Tên class, id phải rõ ràng, gợi nghĩa
Sau đó ta sẽ làm css cho phần này
